name = "website"
main = "cloudflare/worker.js"
route = { pattern = "mirascope.com/*", zone_name = "mirascope.com" }
compatibility_date = "2025-01-01"
[assets]
directory = "./dist"
not_found_handling = "404-page"
[observability]
enabled = true
head_sampling_rate = 1
