name = "website"
main = "cloudflare/worker.js"
route = { pattern = "mirascope.com/*", zone_name = "mirascope.com" }
compatibility_date = "2025-04-01"

[observability]
enabled = true
head_sampling_rate = 1
