name = "website"
main = "cloudflare/country-detection.ts"
routes = [
    { pattern = "mirascope.com/cf/*", zone_name = "mirascope.com" },
    { pattern = "mirascope.com/static/content-meta/*", zone_name = "mirascope.com" },
]
compatibility_date = "2025-04-01"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true
head_sampling_rate = 1
