blank_issues_enabled: true
contact_links:
  - name: 💬 Join Community
    url: "https://mirascope.com/discord-invite"
    about: Join the Mirascope Community to ask questions, get help and chat about Mirascope
