name: ❓ Question
description: Ask a question about anything related to the Mirascope Website
labels: [question]

body:
  - type: textarea
    id: description
    attributes:
      label: Question
      description: How can we help?
    validations:
      required: true
