/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PricingImport } from './routes/pricing'
import { Route as IndexImport } from './routes/index'
import { Route as DocsIndexImport } from './routes/docs.index'
import { Route as BlogIndexImport } from './routes/blog.index'
import { Route as DocsSplatImport } from './routes/docs.$'
import { Route as BlogSlugImport } from './routes/blog.$slug'
import { Route as DocsProductSplatImport } from './routes/docs.$product.$'
import { Route as DocsProductApiSplatImport } from './routes/docs.$product.api.$'

// Create/Update Routes

const PricingRoute = PricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocsIndexRoute = DocsIndexImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any)

const DocsSplatRoute = DocsSplatImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRoute,
} as any)

const BlogSlugRoute = BlogSlugImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRoute,
} as any)

const DocsProductSplatRoute = DocsProductSplatImport.update({
  id: '/docs/$product/$',
  path: '/docs/$product/$',
  getParentRoute: () => rootRoute,
} as any)

const DocsProductApiSplatRoute = DocsProductApiSplatImport.update({
  id: '/docs/$product/api/$',
  path: '/docs/$product/api/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingImport
      parentRoute: typeof rootRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugImport
      parentRoute: typeof rootRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatImport
      parentRoute: typeof rootRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexImport
      parentRoute: typeof rootRoute
    }
    '/docs/$product/$': {
      id: '/docs/$product/$'
      path: '/docs/$product/$'
      fullPath: '/docs/$product/$'
      preLoaderRoute: typeof DocsProductSplatImport
      parentRoute: typeof rootRoute
    }
    '/docs/$product/api/$': {
      id: '/docs/$product/api/$'
      path: '/docs/$product/api/$'
      fullPath: '/docs/$product/api/$'
      preLoaderRoute: typeof DocsProductApiSplatImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/$product/$': typeof DocsProductSplatRoute
  '/docs/$product/api/$': typeof DocsProductApiSplatRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/$product/$': typeof DocsProductSplatRoute
  '/docs/$product/api/$': typeof DocsProductApiSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/$product/$': typeof DocsProductSplatRoute
  '/docs/$product/api/$': typeof DocsProductApiSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/blog/$slug'
    | '/docs/$'
    | '/blog'
    | '/docs'
    | '/docs/$product/$'
    | '/docs/$product/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/blog/$slug'
    | '/docs/$'
    | '/blog'
    | '/docs'
    | '/docs/$product/$'
    | '/docs/$product/api/$'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/blog/$slug'
    | '/docs/$'
    | '/blog/'
    | '/docs/'
    | '/docs/$product/$'
    | '/docs/$product/api/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DocsSplatRoute: typeof DocsSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsProductSplatRoute: typeof DocsProductSplatRoute
  DocsProductApiSplatRoute: typeof DocsProductApiSplatRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  BlogSlugRoute: BlogSlugRoute,
  DocsSplatRoute: DocsSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsProductSplatRoute: DocsProductSplatRoute,
  DocsProductApiSplatRoute: DocsProductApiSplatRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pricing",
        "/blog/$slug",
        "/docs/$",
        "/blog/",
        "/docs/",
        "/docs/$product/$",
        "/docs/$product/api/$"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pricing": {
      "filePath": "pricing.tsx"
    },
    "/blog/$slug": {
      "filePath": "blog.$slug.tsx"
    },
    "/docs/$": {
      "filePath": "docs.$.tsx"
    },
    "/blog/": {
      "filePath": "blog.index.tsx"
    },
    "/docs/": {
      "filePath": "docs.index.tsx"
    },
    "/docs/$product/$": {
      "filePath": "docs.$product.$.tsx"
    },
    "/docs/$product/api/$": {
      "filePath": "docs.$product.api.$.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
