name: External Link Check

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Mondays
  workflow_dispatch: # Allow manual triggers

jobs:
  check-external-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Install dependencies
        run: bun install
        
      - name: Build site
        run: bun run build
        
      - name: Check external links
        id: check-links
        run: bun run scripts/validate-external-links.ts
        
      - name: Upload JSON report
        uses: actions/upload-artifact@v3
        with:
          name: external-link-report-json
          path: external-links-report.json
          if-no-files-found: ignore
      
      - name: Upload Markdown report
        uses: actions/upload-artifact@v3
        with:
          name: external-link-report-md
          path: external-links-report.md
          if-no-files-found: ignore
      
      # Create or update an issue if broken links found
      - name: Create issue for broken links
        if: ${{ steps.check-links.outputs.has_broken_links == 'true' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: External Broken Links Report
          content-filepath: ./external-links-report.md
          labels: report, maintenance
          # If you want to update an existing issue instead of creating a new one:
          # issue-number: ${{ steps.find-issue.outputs.issue-number }}