name: Python Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions to create comments on PRs
permissions:
  contents: read
  pull-requests: write

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Make script executable
      run: chmod +x ./scripts/validate-snippets.sh
      
    - name: Create virtual environment
      run: uv venv
      
    - name: Install dependencies and run validation
      run: ./scripts/validate-snippets.sh --verbose
      
    - name: Add comment when validation fails (PR only)
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue, repo } = context;
          github.rest.issues.createComment({
            issue_number: issue.number,
            owner: repo.owner,
            repo: repo.repo,
            body: "❌ Python validation failed for code snippets.\n\nPlease check the GitHub Actions log for details and fix the errors in the extracted snippets.\n\nCommon fixes:\n1. Make sure all code blocks in MDX files have necessary imports\n2. Fix type annotations in the code\n3. Fix code style issues if any are reported\n4. Update the snippets with `npm run update-snippets`"
          });